
flask:
  SQLALCHEMY_DATABASE_URI: "postgresql://eric:password@localhost/transit_dev"
  SQLALCHEMY_TRACK_MODIFICATIONS: false
  DEBUG: true

import_dir: "mbta_info.flaskr"

mbta_data:
  path: "mbta_info/data"
  files_url: "https://cdn.mbta.com/MBTA_GTFS.zip"
  files:  # table names mapped to data file names
    agency: "agency.txt"
    calendar: "calendar.txt"
    calendar_attribute: "calendar_attributes.txt"
    checkpoint: "checkpoints.txt"
    direction: "directions.txt"
    line: "lines.txt"
    route_pattern: "route_patterns.txt"
    route: "routes.txt"
    shape: "shapes.txt"
    stop_time: "stop_times.txt"
    stop: "stops.txt"
    trip: "trips.txt"
