
flask:
  SQLALCHEMY_DATABASE_URI: "postgresql://eric:password@localhost/transit_test"
  SQLALCHEMY_TRACK_MODIFICATIONS: false
  DEBUG: true
  TESTING: true

import_dir: "mbta_info.tests"

mbta_data:
  path: "mbta_info/data"
  files_url: "https://cdn.mbta.com/MBTA_GTFS.zip"
  files:  # table names mapped to data file names
    geo_stub: "geo_stubs.txt"
    test_model: "test_models.txt"
