version: "3.8"
services:
  app:
    build: .
    image: &app_img app:1.0
    command: ["flask", "run"]
    environment: &app_env
      - FLASK_ENV=docker
      - FLASK_APP=main
    depends_on:
      - postgres
    restart: "no"

  worker:
    build: .
    image: *app_img
    command: ["celery", "-A", "flaskr.mbta_celery.app", "worker" ,"-l", "info"]
    environment: *app_env
    depends_on:
      - beat
      - rabbit
      - postgres
    restart: "no"

  beat:
    build: .
    image: *app_img
    command: ["celery", "-A", "flaskr.mbta_celery.app","beat"]
    environment: *app_env
    depends_on:
      - rabbit
      - postgres
    restart: "no"

  rabbit:
    image: rabbitmq:3.7

  postgres:
    image: postgis/postgis
    volumes:
      - .:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=password
